import 'package:jaspr/dom.dart';
import 'package:jaspr/server.dart';

import 'app.dart';
import 'core/config/site_config.dart';
// Generated by jaspr_builder the first time you run `jaspr serve` / `jaspr build`.
// Red squiggle before that first run is expected.
import 'main.server.options.dart';

/// The site is a single committed dark theme built on two tones — there is no
/// light palette and no toggle, so there is also no theme-boot script and no
/// flash to guard against. The `dark` class and `localStorage` read that used
/// to live here are gone with it.
void main() {
  Jaspr.initializeApp(options: defaultServerOptions);

  runApp(
    const Document(
      title: '${SiteConfig.name} · ${SiteConfig.role}',
      lang: 'en',
      meta: {
        'description': SiteConfig.tagline,
        'author': SiteConfig.name,
        'theme-color': '#282739',
        'color-scheme': 'dark',
      },
      head: [
        // The mark is photographic, so these are PNG rather than the SVG that
        // stood in before. Each is composited onto the site ground with
        // rounded corners — a transparent favicon vanishes against browser
        // chrome of a similar tone.
        //
        // **Every declared size is a multiple of 48**, and that is a hard
        // requirement rather than a preference. Google will only use a favicon
        // in a search result if it is square with sides a multiple of 48px, so
        // the 32x32 that used to lead this list was not merely redundant — it
        // was an ineligible candidate offered first, and the result showed the
        // generic globe. Browsers downscale 48 for a tab perfectly well; there
        // is nothing a 32 was doing that is missed.
        //
        // `/favicon.ico` is listed *and* sits at the document root, because
        // Google probes that exact path independently of what is declared
        // here. It was a 404, which removed the fallback as well.
        link(rel: 'icon', href: '/favicon.ico', attributes: {
          'sizes': '48x48',
        }),
        link(rel: 'icon', href: '/favicon-48.png', attributes: {
          'type': 'image/png',
          'sizes': '48x48',
        }),
        link(rel: 'icon', href: '/favicon-192.png', attributes: {
          'type': 'image/png',
          'sizes': '192x192',
        }),
        // 180x180 is Apple's own spec size and is not a multiple of 48. It
        // stays as-is: it is for the iOS home screen, not for search, and the
        // compliant sizes above mean Google never needs to fall back to it.
        link(rel: 'apple-touch-icon', href: '/apple-touch-icon.png'),
        link(rel: 'preconnect', href: 'https://fonts.googleapis.com'),
        link(
          rel: 'preconnect',
          href: 'https://fonts.gstatic.com',
          attributes: {'crossorigin': ''},
        ),
        link(
          rel: 'stylesheet',
          href: 'https://fonts.googleapis.com/css2'
              '?family=Inter:wght@400;500;600'
              '&family=Plus+Jakarta+Sans:wght@500;600;700;800'
              '&family=JetBrains+Mono:wght@400;500&display=swap',
        ),
        // Tailwind output, compiled from web/styles.tw.css by jaspr_tailwind.
        link(rel: 'stylesheet', href: '/styles.css'),

        // Only site-wide constants belong in this list — anything here is
        // emitted verbatim and is *not* subject to Jaspr's head-override
        // system, so a page-level tag would duplicate rather than replace it.
        // Per-page canonical, Open Graph and JSON-LD live in `core/seo/`.
        //
        // `twitter:card` is a genuine site-wide constant: every page shares as
        // a large image card, and no page overrides it.
        //
        // The `robots` directive used to sit here too, and that was a bug. It
        // is emitted verbatim, so `/404` and `/thanks` — which set their own
        // `noindex` through `PageMeta` — shipped *both* tags and told crawlers
        // to index and not index the same page. It now lives in `PageMeta`
        // alongside the canonical link, where the override system applies and
        // exactly one directive can survive per page.
        meta(name: 'twitter:card', content: 'summary_large_image'),
      ],
      body: App(),
    ),
  );
}
