import 'package:jaspr/client.dart';

// Generated by jaspr_builder — lists every @client component to hydrate.
import 'main.client.options.dart';

void main() {
  Jaspr.initializeApp(options: defaultClientOptions);

  runApp(const ClientApp());
}
