import 'package:jaspr/dom.dart';
import 'package:jaspr/server.dart';

import 'app.dart';
import 'data/profile.dart';
// Generated by jaspr_builder the first time you run `jaspr serve` / `jaspr build`.
// Red squiggle before that first run is expected.
import 'main.server.options.dart';

/// Runs before paint so the correct theme is applied without a flash.
const _themeBoot = "(function(){try{"
    "var t=localStorage.getItem('theme');"
    "var dark=t?t==='dark':true;"
    "document.documentElement.classList.toggle('dark',dark);"
    "}catch(e){document.documentElement.classList.add('dark');}})();";

void main() {
  Jaspr.initializeApp(options: defaultServerOptions);

  runApp(
    const Document(
      title: '${Profile.name} — ${Profile.role}',
      lang: 'en',
      meta: {
        'description': Profile.tagline,
        'author': Profile.name,
        'theme-color': '#07070b',
      },
      head: [
        link(rel: 'icon', href: '/favicon.svg', attributes: {'type': 'image/svg+xml'}),
        link(rel: 'preconnect', href: 'https://fonts.googleapis.com'),
        link(
          rel: 'preconnect',
          href: 'https://fonts.gstatic.com',
          attributes: {'crossorigin': ''},
        ),
        link(
          rel: 'stylesheet',
          href: 'https://fonts.googleapis.com/css2'
              '?family=Inter:wght@400;500;600;700'
              '&family=Space+Grotesk:wght@500;600;700'
              '&family=JetBrains+Mono:wght@400;500&display=swap',
        ),
        // Tailwind output, compiled from web/styles.tw.css by jaspr_tailwind.
        link(rel: 'stylesheet', href: '/styles.css'),

        // Only site-wide constants belong in this list — anything here is
        // emitted verbatim and is *not* subject to Jaspr's head-override
        // system, so a page-level tag would duplicate rather than replace it.
        // Per-page canonical and Open Graph tags live in `PageMeta`.
        meta(name: 'twitter:card', content: 'summary_large_image'),

        script(content: _themeBoot),
      ],
      body: App(),
    ),
  );
}
